### ISSUE TITLE
Arrange the names in the CONTRIBUTORS.md in alphabetical order

### ISSUE THREAD

**Issue by tinniaru3005** [Your-First-Open-Source-Project/Your-First-Open-Source-Project#123]
**Is your feature request related to a problem? Please describe.**
The names of the CONTRIBUTORS.md file is not arranged in alphabetical order
**Describe the solution you'd like**
- Arrange the names in alphabetical order
- Have a heading (H3) of every alphabet and add all the names starting with that alphabet under that heading
- This will help others in finding the names better and also make the file more organized

**Comment by tinniaru3005** [comment]
Can someone confirm if this can be done? If yes, I would like to work on it.

**Comment by melvincwng** [comment]
Hi @tinniaru3005, this is not required as the community is constantly growing. Hence it would not be practical if a sorted CONTRUBITORS.md was created and newer members might have difficulty adding their names based on their sorted order.

An easier solution would be to just add their names in CONTRIBUTORS.md in numerical order/order of joining instead.
