### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by scarnation** [Your-First-Open-Source-Project/Your-First-Open-Source-Project#89]
Would love to know what the community website would be required to have, that way I can draft a design file via Figma and share the design assets 
-would suggest creating a repository for the community

**Comment by scarnation** [comment]
-highlighting the goals of the organization too would help in designing a site

**Comment by melvincwng** [comment]
@scarnation Hi Oscar, appreciate the enthusiasm for this open source project :)

With regards to the Community Website, this is still in KIV at the moment.

Currently, I'm busy working on other projects, hence I won't be able to dedicate time in the near future to work on the community website.

But do stay tuned to updates to this open source project / organization!

**Comment by scarnation** [comment]
Alright,  looking forward to your updates
